### ISSUE TITLE
Using Filebase

### ISSUE THREAD

**Issue by jamongeon** [vsevdrob/nft-brownie-ipfs-pinata-hashlips#3]
Is it possible to use the Filebase IPFS Pinning API (https://docs.filebase.com/api-documentation/ipfs-pinning-service-api) in place of Pinata?

**Comment by sevamove** [comment]
If the goal is to replace _Pinata_ with any other IPFS pinning service than __yes__, it is possible. In order to achieve this the only thing has to be done is just to replace the values of the [function's](https://github.com/88vsd/nft-brownie-mix/blob/32080aa0eca2ee3143e1845adf0a246bbe148192/scripts/utils/pinata.py#L6) internal variables such as `PINATA_BASE_URL`, `endpoint` and `headers` with the values that in this case _Filebase_ might provide through its documentation.
